version: "3.9"
services:
  cdo-server:
    container_name: cdo-4.20
    stdin_open: true
    tty: true
    # environment:
    build: 
        context: ./
        dockerfile: Dockerfile
    ports:
        - "2036:2036"
    volumes:
        - ./etc/database/:/root/cdo-v4.20/eclipse/database/
    #    - ./etc/configuration/:/root/cdo-v4.20/eclipse/configuration/
    privileged: true
